# .bash_profile

# Get the aliases and functions
if [ -f ~/.bashrc ]; then
        . ~/.bashrc
fi

# User specific environment and startup programs
HISTSIZE=10000

PATH=$PATH:$HOME/bin

export PATH
unset USERNAME
export HISTTIMEFORMAT="%d/%m/%y %T "
export PS1='\[\033[1;34m\][`date +%R`]:\[\033[1;43;36m\]\u@\[\033[1;32m\]\h\[\033[m\]:\W:\[\033[1;31m\]#\[\033[00m\]:>'
export GREP_OPTIONS='--color=auto' GREP_COLOR='101;20'
